baseURL: https://vadim-dmitriev.github.io/
title: Tech Notes
theme: mini
languageCode: ru-ru
contentDir: content

# Default content language, support en (English) / zh (Chinese) / nl (Dutch) / fr (French) / es (Spanish) / da (Danish), default 'en'
defaultContentLanguage: en

# languages:
#   ru:
#     languageCode: ru
#     languageName: Russian
#     params:
#       reading_speed: 179
#     weight: 2

hasCJKLanguage: true
permalinks:
  posts: /posts/:title/

paginate: 3

googleAnalytics: G-FN9GSZ50FE
# disqusShortname: your-disqus-shortname

# Hugo Configure Markup
# More info: https://gohugo.io/getting-started/configuration-markup#
markup:
  highlight:
    guessSyntax: true
    style: emacs
  tableOfContents:
    endLevel: 3
    ordered: false
    startLevel: 2
  # needed to render raw HTML (e.g. <sub>, <sup>, <kbd>, <mark>)
  goldmark:
    renderer:
      unsafe: true


# Social links in footer, support github,twitter,stackoverflow,facebook
social:
  github: https://github.com/vadim-dmitriev
  # TODO: fork theme and add this social.
  # telegram: https://t.me/dva_notes
  # twitter: your-twitter-link
  # stackoverflow: your-stackoverflow-link
  # facebook: your-facebook-link


# Site parameters
params:
  # Site Author
  author: Vadim Dmitriev
  # Author biography
  bio: Go Lead/Software Engineer
  # Site Description, used in HTML meat
  description: This is my personal technical blog
  # darkMode:
  #   enable: true
  readingTime:
      enable: false


  ###########################################
  # Optional Configuration
  ###########################################

  # To enable RSS, you could set `enableRSS: true`, default is `true`
  # enableRSS: true
  # To enable comments, you may need to set `disqusShortname`
  # enableComments: true
  # To enable comments, you may need to set `googleAnalytics`
  # enableGoogleAnalytics: true
  # To enable table of content, you could set `showToc: true`, default is `false`
  # showToc: true
  # To hidden powerBy message in the page footer, you could set: `showPowerBy: false`, default is `true`
  showPowerBy: true
  # To enable math typesetting , you could set `math: true`, default is `false`
  math: false
  # To hidden post summary in home page, you could set `hiddenPostSummaryInHomePage: true`, default is `false`
  hiddenPostSummaryInHomePage: false
  # Website copy write, default: '© Copyright 2021 ❤️ {params.author}'
  copyright: '' 

  # Extra links in navigation
  links:
    ## e.g.
    # - name: Project
    #   path: /project

  # You can put your custom css and js to `static` directory, or use remote css and js files which start with `http://` or `https://`
  customCSS:
    - css/styles.css
  customJS:
    - js/script.js
